//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ModelDBEntities : DbContext
    {
        public ModelDBEntities()
            : base("name=ModelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Summary_table_users_tools> Summary_table_users_tools { get; set; }
        public virtual DbSet<Tools> Tools { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        public virtual ObjectResult<JoinTables_Result> JoinTables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JoinTables_Result>("JoinTables");
        }
    
        public virtual ObjectResult<ToolsQuery_Result> ToolsQuery()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ToolsQuery_Result>("ToolsQuery");
        }
    }
}
