//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Summary_table_users_tools
    {
        public int sid { get; set; }
        public int id_tools { get; set; }
        public int id_users { get; set; }
        public int countTols { get; set; }
    }
}
